version: 2.1
orbs:
  cypress: cypress-io/cypress@3 # use s.x.y version to lock version
  codecov: codecov/codecov@4.0.1

# Executors are the environments in which the jobs run
executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1"

# Commands are reusable steps that can be called by their name
commands:
  report-coverage:
    description: "Store coverage report as an artifact"
    steps:
      - store_artifacts:
          path: coverage
      - run: npm run coverage-report-text
      - codecov/upload:
          file: ./coverage/coverage-final.json
  setup_project_and_cypress:
    steps:
      - cypress/install:
          package-manager: npm
      - run:
          name: Build project
          command: npm run build:instrumented
      - run:
          name: Print machine information
          command: npx cypress info
      - run:
          name: Run Cypress component tests
          command: npm run cypress-run-component
      # - run:
      #     name: Run Cypress e2e tests
      #     command: npm run cypress-run-e2e
      - cypress/run-tests:
          start-command: npm start
          cypress-command: npm run cypress-run-e2e

      - report-coverage

# Jobs are the individual tasks that can be run in parallel
jobs:
  setup_project_and_cypress_linux:
    executor: with-chrome-and-firefox
    steps:
      - setup_project_and_cypress

# Workflows are the sequences of jobs that are run in response to events
linux-workflow: &linux-workflow
  jobs:
    # Setup project and Cypress on Linux
    - setup_project_and_cypress_linux:
        name: Setup project and Cypress on Linux
    # Run Cypress component tests

workflows:
  linux:
    <<: *linux-workflow
