version: 2.1
orbs:
  cypress: cypress-io/cypress@3 # use s.x.y version to lock version
  node: circleci/node@5.0.0

jobs:
  # setup-node:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - node/install:
  #         node-version: "20"

  cypress-run:
    executor: node/default
    steps:
      - checkout
      - cypress/run:
          start-command: "npm run start"
          cypress-command: "npx cypress run --browser chrome"

workflows:
  build:
    jobs:
      # - setup-node
      - cypress-run
