version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.0

jobs:
  setup-node:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: "20"
workflows:
  build:
    jobs:
      - setup-node
      - cypress/run: # "run" job comes from "cypress" orb
          start-command: "npm run start"
